### ISSUE TITLE
AMB82-MINI compilation error.

### ISSUE THREAD

**Issue by Oliver0804** [ambiot/ambpro2_arduino#32]
![截圖 2023-01-02 下午8 53 03](https://user-images.githubusercontent.com/8245980/210234411-d17f74ec-c2af-4888-aa4b-76d5609b9304.png)
Using the RTSP stream in the example...(StreamRTSPSingleVideoWithAudio)
macOS
Arduino 1.8.19
AmebaPro2 4.0.1-build20221222

**Comment by Oliver0804** [comment]
'''
<built-in>: fatal error: opening dependency file /dev/null.d: Operation not permitted
ResolveLibrary(opening dependency file /dev/null.d)compilation terminated.

  -> candidates: []
exit status 1
'''

**Comment by S10143806H** [comment]
Dear @Oliver0804
First of all, the stable version of Arduino SDK is on our `main` branch, kindly noted that the `dev` branch is still under development.
Secondly, if you encounter any similar error in the downloaded `main` branch Arduino SDK, help build an empty example .ino first due to cached compiled data will cause the compilation to fail.
Thank you.

**Comment by M-ichae-l** [comment]
Closed. As there is no further issue.
