### ISSUE TITLE
[BOOT Err]Invalid Image Mani Label

### ISSUE THREAD

**Issue by amigomcu** [ambiot/ambpro2_arduino#82]
hi all,

i use empty example .ino to build and program success.

BootFromNORFlash
[Start Boot ROM...]
=== Load PARTBL ===

[BOOT Err]Invalid Image Mani Label!

[BOOT Err]StartUp@0x0: Invalid RAM Img Signature!Boot_err(0x11

windows 10,
arduino ide, 2.0.4
AmebaPro2,v4.0.2

it seem as program flash parameters setting issue?
my setting:
![image](https://user-images.githubusercontent.com/23089799/231344365-3b7d3977-2499-4107-964e-a110e7728809.png)

same issue:
https://forum.amebaiot.com/t/rtl8720c-flash-log/1239

**Comment by S10143806H** [comment]
Dear @amigomcu ,

- Firstly, the Auto Flash Mode is not supported on the AMB82-MINI board, you should Disable it.
- Secondly, since you want to upload an empty .ino sketch into your board, the Erase Flash option should also be set to Disable.

To summarize, please set your menu as shown below for uploading: 

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/9852678/231356571-601e4275-f351-4b23-962a-8e7ac4877daf.png)

Thanks.
